@HostAddress = http://localhost:5034

# Get all houses
GET {{HostAddress}}/houses/
Accept: application/json

###
# Get one houses
GET {{HostAddress}}/houses/01956caf-381a-4ca3-8d36-5be04ecbf258
Accept: application/json

###
# Create a house
POST {{HostAddress}}/houses
Accept: application/json
Content-Type: application/json

{
  "name": "Test",
  "address": "My super address",
  "numberOfRooms": 12
}

###
# Get a specific house
PUT {{HostAddress}}/houses/
Accept: application/json
Content-Type: application/json

{
  "address": "My v2 new hyper cool address"
}